readme scripts table

diff --git a/scripts/btcs-extended-key-path b/scripts/btcs-extended-key-path
--- a/scripts/btcs-extended-key-path
+++ b/scripts/btcs-extended-key-path
@@ -1,9 +1,20 @@
 #!/bin/sh
 
 info=$(cat << EOF
-btcs extended-key-path core-wallet private|public|descriptor
+btcs extended-key-path core-wallet private|public|descriptor [desc-number]
 EOF
 )
+
+is_uint() {
+    case "$1" in
+        ''|*[!0-9]*)
+            return 1
+        ;;
+        *)
+            return 0
+        ;;
+    esac
+}
 
 if [ "$#" -ge 1 ]; then
     case "$1" in
@@ -21,6 +32,17 @@ fi
 wallet="$1"
 mode="$2"
 shift 2
+
+desc_number=1
+if [ "$#" -ge 1 ]; then
+    desc_number="$1"
+    shift 1
+
+    if ! is_uint "$desc_number"; then
+        echo "error: $desc_number is not an unsigned int" >&2
+        exit 1
+    fi
+fi
 
 if ! $BTC_BIN listwallets | jq -r '.[]' | grep "^${wallet}$" >/dev/null; then
     echo "error: wallet $wallet does not exists or is not loaded" >&2
@@ -46,13 +68,15 @@ case "$mode" in
     private|public)
         $BTC_BIN -rpcwallet="$wallet" listdescriptors "$mode_bool" |
         jq -r '.descriptors[].desc' |
-        head -n 1 |
+        head -n "$desc_number" |
+        tail -n 1 |
         rev | cut -d "(" -f 1 | rev |
         cut -d ")" -f 1
     ;;
     descriptor)
         $BTC_BIN -rpcwallet="$wallet" listdescriptors |
         jq -r '.descriptors[].desc' |
-        head -n 1
+        head -n "$desc_number" |
+        tail -n 1
     ;;
 esac
